/*
  The DB2 data on the Carolina lpars are DB2SMF, hence
   they can be processed using the TYPEDB2/TYPSDB2 member.
   There is no need to expand the data.                   */

%include '/var/opt/local/perf/mxg/programs/car_ftp.sas'; /* Contains FTP parms */

filename smf ftp "'CPL.SOS.TMDB.CIMS.DB2SMF.ARCHIVE(-0)'"
	_carftp
;

libname  db2      '/var/opt/local/perf/mxg/daily/db2/cims';

 /* This section of code forces MXG to create DB2ACCT and DB2STATS data only.
    All other DB2 datasets will be _NULL_ out.
    The Performance group tailored the DB2 processing this way because the
    DB2 datasets can be quite large and take significantly longer to process. */

/*  This macro contains all the variables to drop from the 
    DB2ACCT and ASUMDB2A datasets  */
%let kdb2acc = %quote (
DROP=
DB2SRBTM  QB1CBPX   QB1CDPF   QB1CHPG   QB1CHRE   QB1CHRF   QB1CHWF   QB1CHWR
QB1CIMW   QB1CLPF   QB1CPID   QB1CRIO   QB1CSEQ   QB1CSIO   QB1CSWS   QB2CBPX
QB2CDPF   QB2CHPG   QB2CHRE   QB2CHRF   QB2CHWF   QB2CHWR   QB2CIMW   QB2CLPF
QB2CPID   QB2CRIO   QB2CSEQ   QB2CSIO   QB2CSWS   QB3CBPX   QB3CDPF   QB3CHPG
QB3CHRE   QB3CHRF   QB3CHWF   QB3CHWR   QB3CIMW   QB3CLPF   QB3CPID   QB3CRIO
QB3CSEQ   QB3CSIO   QB3CSWS   QB4CBPX   QB4CDPF   QB4CHPG   QB4CHRE   QB4CHRF
QB4CHWF   QB4CHWR   QB4CIMW   QB4CLPF   QB4CPID   QB4CSEQ   QB4CSIO   QB4CSWS
QBGA2H    QBGA2S    QBGA2W    QBGADG    QBGAEX    QBGAGG    QBGAGN    QBGAHS
QBGAMD    QBGAMN    QBGAMR    QBGAP1    QBGAP2    QBGAP3    QBGAS1    QBGAS2
QBGAS3    QBGASW    QBGAWC    QBGAWS    QBGAXD    QBGAXN    QBGAXR    QIFAAIET
QIFAAITT  QIFAAMBT  QIFAAMLT  QIFAANDD  QIFAANDR  QIFAANIF  QIFAANLR  QIFAANMB
QIFAANRC  QIFAANRR  QIFAANTB  QLACBKRC  QLACBKSE  QLACBRBF  QLACBROW  QLACBTBF
QLACBYTR  QLACBYTS  QLACCBLB  QLACCIEL  QLACCNVA  QLACCNVQ  QLACCNVR  QLACCNVS
QLACCNVT  QLACCPUL  QLACCPUR  QLACDBAT  QLACFLA1  QLACFLA2  QLACFLG1  QLACFLG2
QLACINDT  QLACLARC  QLACLASE  QLACLOCN  QLACMDWT  QLACMSGR  QLACMSGS  QLACOFF1
QLACPRID  QLACPRRC  QLACPRSE  QLACRBTR  QLACROWR  QLACROWS  QLACRRRC  QLACRRSE
QLACTRNR  QLACTRNS  QLACVNRC  QLACVNSE  QLACVYRC  QLACVYSE  QMDAASLN  QMDALUNM
QMDANETN  QMDAPMOD  QMDASFLN  QTGACPLK  QTGACSLM  QTGADRTA  QTGAIGLO  QTGALPLK
QTGALSLM  QTGANTFY  QTGASGLO  QTGAUPLK  QTGAUSLM  QTXACHUS  QTXACLMT  QTXACLNO
QTXACLUN  QTXADRNO  QTXADRUN  QTXAFLG1  QTXAILMT  QTXAIRLM  QTXALES   QTXALEX
QTXANRUN  QTXAPREC  QTXASLAT  QTXASLMT  QWACAJST  QWACALCT  QWACALOG  QWACANAR
QWACARNA  QWACARNC  QWACARNG  QWACARNK  QWACARNM  QWACARNN  QWACARNQ  QWACARNS
QWACASRB  QWACAWCL  QWACAWTE  QWACAWTG  QWACAWTK  QWACAWTM  QWACAWTN  QWACAWTO
QWACAWTQ  QWACBJST  QWACBSC   QWACBSRB  QWACCANM  QWACCAST  QWACDSNS  QWACDSSE
QWACEJST  QWACESC   QWACESRB  QWACFLGS  QWACIXLE  QWACIXLT  QWACLRAB  QWACLRN
QWACOCNS  QWACOTNS  QWACOTSE  QWACPACE  QWACPARR  QWACPCNT  QWACPECT  QWACPKGN
QWACRBSV  QWACRINV  QWACRLSV  QWACSLNS  QWACSLSE  QWACSPCP  QWACSPEA  QWACSPEB
QWACSVPT  QWACTREE  QWACTRET  QWACTRTE  QWACTRTT  QWACUDCP  QWACUDST  QWAXALCT
QWAXALOG  QWAXANAR  QWAXARNC  QWAXARND  QWAXAWCL  QWAXAWDR  QWAXDSNS  QWAXDSSE
QWAXIXLE  QWAXIXLT  QWAXOCNS  QWAXOCSE  QWAXOTNS  QWAXOTSE  QWAXSLNS  QWAXSLSE
QWDAXCQO  QWHDSVNM  QWHDTSTP  QWHDUNIQ  QWHSACE   QWHSIID   QWHSISEQ  QWHSLOCN
QWHSLUCC  QWHSLUCN  QWHSLUUV  QWHSMTN   QWHSSIID  QWHSSTCK  QWHSWSEQ  QXALDAB
QXALOCC   QXALOCL   QXALPRO   QXALTIX   QXALTSEQ  QXALTST   QXALTTA   QXALTTS
QXALTVW   QXALUDF   QXCAUD    QXCAUDAB  QXCAUDRJ  QXCAUDTO  QXCDIST   QXCLOSE
QXCMTON   QXCON1    QXCON2    QXCOORNO  QXCRALS   QXCRATB   QXCRDAB   QXCRESEQ
QXCRGTT   QXCRINDX  QXCRPRO   QXCRSTG   QXCRSYN   QXCRTAB   QXCRUDF   QXCTABS
QXCTRIG   QXDCLGTT  QXDDIST   QXDEFVU   QXDEGBUF  QXDEGCUR  QXDEGDTT  QXDEGENC
QXDEGESA  QXDELET   QXDESC    QXDROSEQ  QXDRPAL   QXDRPDB   QXDRPFN   QXDRPIX
QXDRPPKG  QXDRPPR   QXDRPST   QXDRPSY   QXDRPTA   QXDRPTR   QXDRPTS   QXDRPVU
QXDSCRTB  QXFETCH   QXFREEL   QXGRANT   QXHOLDL   QXINCRB   QXINSRT   QXISORR
QXLABON   QXLOCK    QXMAXDEG  QXMIAP    QXMRMIAP  QXMSMIAP  QXNORGRP  QXNSMIAP
QXOPEN    QXPREP    QXPRRESI  QXREDGRP  QXREL     QXREPOP1  QXREPOP2  QXREVOK
QXRLFDPA  QXRNTAB   QXROIIDX  QXROIMAT  QXROITS   QXROWTRG  QXSELECT  QXSETCDG
QXSETCON  QXSETCPR  QXSETCRL  QXSETHV   QXSETPTH  QXSTDEXP  QXSTDINV  QXSTFND
QXSTIPRP  QXSTLOBV  QXSTNFND  QXSTNPRP  QXSTREOP  QXSTTRG   QXTOTGRP  QZZCBPNX
QZZCSKIP
  );

                   %LET MACKEEP=
                     %QUOTE(
                           _NDB2
                           MACRO _WDB2ACC _LDB2ACC %
                           MACRO _WDB2ST0 DB2STAT0 %
                           MACRO _WDB2ST1 DB2STAT1 %
                           MACRO _WDB2STB DB2STATB %
                           MACRO _SDB2 _SDB2STB _SDB2STS %
                           MACRO _SDB2ACP %
                           MACRO _SDB2ACB %
                           MACRO _SDB2ACG %
                           MACRO _SDB2PAT %
                           MACRO _SDB2ST2 %
                           MACRO _SDB2STR %
                           MACRO _SDB2PST %
			   );
   %let pdb2acc = db2;
   %let psudb2a = db2;
   %LET PDB2ST0=WORK;
   %LET PDB2ST1=WORK;
   %LET PDB2STB=WORK;
   %let pdb2sts=db2;

%include sourclib(typsdb2);
%include sourclib(asumdb2a);
